### ISSUE TITLE
Cannot find module 'gulp-util'

### ISSUE THREAD

**Issue by harshabhat14** [gulpjs/gulp-util#154]
For gulp war i am getting below error
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/nodejs/gulp/bin/gulp.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

After i tried so many times node version and npm install.

**Comment by demurgos** [comment]
I don't think it's a `gulp` or `gulp-util` issue but a problem with `npm` or one of your dependencies.

Your issue is not actionable as it is: it's missing a lot of context:
What is your gulp version, is `gulp-util` in your `node_modules` directory (if so which version?), which Gulp plugins are you using (and which version), are you using `gulp-cli`, how are you executing your tasks? What is even "gulp war"?

`gulp-util` is deprecated. Most popular plugins have moved away from it. Make sure that your plugins are still maintained, use their latest version.

**Comment by kedar8** [comment]
From later versions, there is no need to manually install gulp-util.

Check to get`[started page](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md).`

If you still hit this problem try reinstalling your project's local packages:

**rm -rf node_modules/**
**npm install**

if u want to install manually : -
You also need to install gulp-util:
 **npm install gulp-util --save-dev**

**Comment by allafridman** [comment]
I cannot build this either
