### ISSUE TITLE
Error 'Arguments to path.join must be strings' when trying to pipe after gutil.buffer()

### ISSUE THREAD

**Issue by dualcyclone** [gulpjs/gulp-util#62]
I am trying to use gutil to filter a set of files, but it seems if I attempt to pipe after an empty call to buffer, I receive the above error.

My source is fairly simple...
<pre><code>gulp.src([
    './**/*.scss'
])
.pipe(gutil.buffer(function (err, files) {
    // Nothing, its just empty
}))
.pipe(sass({
    style: 'expanded',
    debugInfo: false,
    noCache: true
}))</code></pre>

And I receive the following error:

<pre><code>path.js:204
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Transform.transform._transform (\node_modules\gulp-ruby-sass\node_modul
es\gulp-intermediate\index.js:27:29)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Transform.Writable.write (_stream_writable.js:183:11)
    at write (\node_modules\gulp-util\node_modules\through2\node_modules\reada
ble-stream\lib\_stream_readable.js:623:24)</code></pre>

Removing the pipe for the buffer allows this task to function as expected.

So, I want to know, am I using the buffer function incorrectly? 
Can I actually filter the file list before sending it on to the next piped task? 
Is this a genuine error or is it just my misunderstanding on how to use it?

...Forgive me if this isn't a genuine error, I just can't seem to find any valid usages of this method.

**Comment by phated** [comment]
Closing as I believe it was addressed above ^
