### ISSUE TITLE
PluginError and inconsistent showStack output

### ISSUE THREAD

**Issue by shellscape** [gulpjs/gulp-util#65]
Following the examples, I'm constructing an error as such:

```
  var gutil = require('gulp-util');

  swig.error = function (entityName, message) {
    var err = new Error(message);
    return new gutil.PluginError(entityName, err, { showStack: true });
  }

  throw swig.error('publish-verify', 'Testing errors');
```

The output that's generated between constructors is pretty inconsistent. Using the constructor above results in a redundant 'Message:', since it's repeated at the top of the stack that's rendered, and a phantom 'Stack:' section with no content.

```
[09:40:55] Starting 'publish-verify'...
[09:40:55] 'publish-verify' errored after 2.72 ms
[09:40:55] Error in plugin 'publish-verify'
Message:
    Testing errors
Stack:
Error: Testing errors
    at Object.swig.error (/Users/[...]/utilities/swig-util/lib/error.js:21:15)
    at Gulp.publishVerifyTask (/Users/[...]/tasks/swig-publish/index.js:29:16)
    at module.exports (/Users/[...]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/[...]/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/[...]/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/[...]/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/[...]/.nvm/v0.11.13/lib/node_modules/gulp/bin/gulp.js:121:20
    at process._tickCallback (node.js:343:11)
    at Function.Module.runMain (module.js:492:11)
    at startup (node.js:124:16)
```

(Granted that the first line in the stack points to my utility function, that's expected)

If I change the utility function to use a different constructor signature (again based on the samples) to:

```
  var gutil = require('gulp-util');

  swig.error = function (entityName, message) {
    return new gutil.PluginError(entityName, message, { showStack: true });
  }

  throw swig.error('publish-verify', 'Testing errors');
```

I get the following output:

```
[09:59:24] Starting 'publish-verify'...
[09:59:24] 'publish-verify' errored after 531 μs
[09:59:24] Error in plugin 'publish-verify'
Error
    at Object.swig.error (/Users/[...]/utilities/swig-util/lib/error.js:21:12)
    at Gulp.publishVerifyTask (/Users/[...]/tasks/swig-publish/index.js:29:16)
    at module.exports (/Users/[...]/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/[...]/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/[...]/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/[...]/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/[...]/.nvm/v0.11.13/lib/node_modules/gulp/bin/gulp.js:121:20
    at process._tickCallback (node.js:343:11)
    at Function.Module.runMain (module.js:492:11)
    at startup (node.js:124:16)
```

The message is now missing and isn't displayed anywhere, the phantom empty 'Stack:' isn't rendered (yay) but the rendered stack is just prefixed with 'Error'. Inconsistencies like this may not be a big deal on the surface, but it makes tying in any kind of reporting utility on build errors a hefty task due to the different forms of output from different constructors (and data) used. Ideally, this should be uniform.

**Comment by demurgos** [comment]
Closing due to inactivity. Please reopen at [gulpjs/plugin-error](https://github.com/gulpjs/plugin-error) if needed.
